dist: trusty

sudo: true

language: python

matrix:
  include:
      - os:linux
        # add under env? --> DISPLAY=:99.0 AUDIODEV=null
        env: PYTHON_VERSION=3.6

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
    - conda env create -f environment.yml
    - source activate psypy3
    - pip install -e .

script:
    - pytest --cov=sp_experiment --verbose

after_success:
- bash <(curl -s https://codecov.io/bash)
