
name: psypy3
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- numpy
- scipy
- matplotlib
- pandas
- pip:
  - pyopengl
  - pyglet
  - pillow
  - moviepy
  - lxml
  - openpyxl
  - configobj
  - psychopy==3.0.0
